### ISSUE TITLE
Reimplement changes undone by #103 (always use raw response data)

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-resumable-media-python#106]
Changes originally merged in #87 were undone in #103 in a way that can be opted in to to avoid breaking usage by users on older client library versions. Particularly GCS

**Comment by crwilcox** [comment]
This issue over on GCS, https://github.com/googleapis/google-cloud-python/issues/9188, seems to point to us making it more clear when we are decompressing and what the encoding is.

**Comment by tseaver** [comment]
See PR #87.  Note that redoing them is complicated by the fact that the code has since been blackened. :(

**Comment by tseaver** [comment]
Plan:

- [ ] Restore partial fix for #56. (PR #107).
- [ ] Split out decoding vs. raw-only behavior into separate classes.
