### ISSUE TITLE
RuntimeError: consume() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by richardo-ps** [googleapis/google-resumable-media-python#148]
Release 0.7.0 is broken and needs to be rolled back to 0.6.0. 

```
RuntimeError: consume() got an unexpected keyword argument 'timeout'
```

Temporary fix:

```
pip uninstall google-resumable-media
pip uninstall google-cloud-storage
pip install google-resumable-media==0.6.0
pip install google-cloud-storage==1.30.0
```

**Comment by busunkim96** [comment]
@crwilcox @frankyn Could you take a look?

**Comment by busunkim96** [comment]
@richardo-ps Can you provide a more detailed stack trace?

**Comment by richardo-ps** [comment]
```
    blob.download_to_file(data_raw)
  File "/env/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1005, in download_to_file
    timeout=timeout,
  File "/env/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 872, in _do_download
    response = download.consume(transport, timeout=timeout)
TypeError: consume() got an unexpected keyword argument 'timeout'
```

**Comment by frankyn** [comment]
Hi @richardo-ps, thanks for the additional information.

I tried to reproduce the error you're seeing but haven't been successful.

Could you try the following:

1. `pip install virtualenv`
1. `virtualenv repro_env`
1. `source repro_env/bin/activate`
1. `pip install google-resumable-media==0.7.0`
1. `pip install google-cloud-storage=1.30.0`
1. Run your example code.


In your follow-up post could you share the following:

1. Share the example you're using to reproduce the issue.
1. Add the Python version you're using.
1. Add virtualenv dependency veresions using `pip freeze` as well.

Thank you for your patience.

**Comment by tseaver** [comment]
Please feel free to follow up / reopen if more information becomes available.
