### ISSUE TITLE
Maximum chunk size for ResumableUpload?

### ISSUE THREAD

**Issue by kaleb-utilityapi** [googleapis/google-resumable-media-python#209]
I was looking at the documentation regarding chunk size for [ResumableUpload](https://github.com/googleapis/google-resumable-media-python/blob/master/google/resumable_media/requests/upload.py#L153) because I'm seeing some poor upload performance (< 25 Mb/s upload speeds) on a 5 Gb/s interface. 

I notice in the examples that the chunk sizes are all 3 MB, but we're using much larger chunks (100 MB). Some more investigation lead me to [this comment](https://github.com/googleapis/google-api-python-client/issues/793#issuecomment-571786008) about another library mentioning in the docstring that the max chunk size is 5 MB. I assume that this also applies here since it doesn't look like anything particularly fancy is going on in the `ResumableUpload` class, but I wanted to double check.

Should this also be included in the docstrings here?

**Comment by andrewsg** [comment]
Hi, sorry this question slipped through the cracks for so long. The request size limit discussed is a specific limit for some Google App Engine requests. It is not related to Google Cloud Storage or resumable media through this library, even if Storage is accessed from a Google App Engine instance. If you are experiencing slow upload speeds, I don't think I can clearly attribute that to any particular chunk size, but experimenting with a smaller chunk size could be worthwhile as the per-request overhead is minimal above a few megabytes.
