### ISSUE TITLE
Noxfile is not updated with Sphinx version pin

### ISSUE THREAD

**Issue by dandhlee** [googleapis/google-resumable-media-python#223]
`noxfile.py` is not updated with Sphinx version pin, please help take a look!

**Comment by parthea** [comment]
This repo is not using the templated version of `noxfile.py` so I've opened a PR just to set the `sphinx` version to `4.0.1`

**Comment by dandhlee** [comment]
Sounds good, I'll leave a note to look after this repo manually for now.
