### ISSUE TITLE
Header parsing should be checking for string type header values

### ISSUE THREAD

**Issue by cojenco** [googleapis/google-resumable-media-python#233]
As documented [here](https://github.com/googleapis/google-resumable-media-python/blob/73080754bf435b49784c67a2363a7b0614222a22/google/resumable_media/_helpers.py#L53-L54), an HTTP response object `headers` attribute is a ``Mapping[str, str]`

[`_helpers._parse_checksum_header`](https://github.com/googleapis/google-resumable-media-python/blob/73080754bf435b49784c67a2363a7b0614222a22/google/resumable_media/_helpers.py#L301) therefore should also be checking for string type "None" values.

**Comment by tseaver** [comment]
I'm not sure I buy the argument here:  Are we actually expecting the GCS back-end to return a header like `x-goog-hash: None`?  The [docs for the `x-goog-hash` header] state:

> Cloud Storage stores MD5 hashes for all non-composite objects. CRC32Cs are available for all objects.

Which would seem to imply that the response header value is *always* going to have at least the `crc32c` member.

**Comment by cojenco** [comment]
That makes sense! Thanks for pointing it out. I was confused by the simulated response from the storage emulator. I'll close this issue and make changes to the emulator so it fits this behavior.
