### ISSUE TITLE
Using a signed Resumable Upload URL fails with 403 unless content_type is empty

### ISSUE THREAD

**Issue by williambrode** [googleapis/google-resumable-media-python#289]
#### Environment details

  - Programming language: Python
  - OS: Ubuntu 20.04 in WSL2
  - Language runtime version: 3.8
  - Package version: cee416449701b72e7fd532585a1f739b02b6ab32

#### Steps to reproduce

  1. Generate a signed resumable upload url:
```
gsutil signurl -m RESUMABLE -c application/octet-stream -d 24h <key_file> gs://<bucket>/<obj>
```
  2. Run this python program, passing in the upload_url that was generated:
``` python
import io

from google.resumable_media import InvalidResponse
from google.resumable_media.requests import ResumableUpload
from requests import Session

chunk_size = 16 * 1024 * 1024  # 16MB

upload = ResumableUpload(upload_url, chunk_size)
stream = io.BytesIO(data)
metadata = {}
transport = Session()
transport.headers.update({'x-goog-resumable': 'start'})
try:
	response = upload.initiate(
		transport, stream, metadata, 'application/octet-stream')
except InvalidResponse as err:
	print(err.response.content)
	raise
print(response)
while not upload.finished:
	upload.transmit_next_chunk(transport)
stream.close()
```

You will get a 403 error from google that says `The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.`.  This is because the content_type passed by the library to the signed url is not correct.  If you instead generate the url without a content_type - it will succeed - but the object will have the content type `application/json`.  I'll send in a PR shortly with a fix that works for me.

**Comment by williambrode** [comment]
@tseaver Any chance we could cut a release so I can switch back to the community version?  Trying to do commit shas with pip is giving us headaches!

**Comment by tseaver** [comment]
@williambrode I'm not a maintainer here any longer.  @andrewsg or @cojenco could likely push out a release, though.

**Comment by cojenco** [comment]
@williambrode We just cut a new release v2.2.0 this morning. Thanks for your patience!
