### ISSUE TITLE
After retry limit reached, ResumableUpload.transmit_next_chunk propagates exception with invalid==False

### ISSUE THREAD

**Issue by AshleyT3** [googleapis/google-resumable-media-python#324]
The code below with comments probably best describes the issue... it shows two workarounds. A third workaround (not shown) might be to look for a retry timeout exception and assume the ResumableUpload is invalid despite it being in a recoverable state in my various tests. I'm wondering if a call to _make_invalid upon final retry limit reached is reasonable, or perhaps documenting implied invalidity after retry limit though the latter would seem odd since a retry limit having been reached is not equivalent to a non-recoverable state. 

```
upload = ResumableUpload(upload_url, chunk_size)
response = upload.initiate(transport=session, 
                            stream=stream, 
                            metadata=metadata, 
                            content_type="application/octet-stream", 
                            stream_final=False)
while not upload.finished:
    try:
        pos_before_xmit = stream.tell()
        upload.transmit_next_chunk(session)
    except Exception as ex:
        bytes_attempted = stream.tell() - pos_before_xmit
        """ 
        #
        # I first tried the following which skips recover
        # and jumps back to transmit_next_chunk above.
        # Without this, transmit_next_chunk fails. This
        # seems somewhat equivalent to continuing
        # above with retry reset.
        #
        if not upload.invalid:
            stream.seek(pos_before_xmit, io.SEEK_SET)
        else:
            r = upload.recover(session)
        """
        #
        # After looking at internals, I tried this which
        # also worked. Without the _make_invalid call,
        # recover fails and the stream is not rewound,
        # causing transmit_next_chunk to fail. 
        #
        if not upload.invalid:
            upload._make_invalid() # not really supposed to be called by users.
        r = upload.recover(session)
        # etc.
```

An aside, thanks to authors/contribs who created ResumableUpload.

**Comment by cojenco** [comment]
Hi @AshleyT3 thanks for raising the question. Could you share the exception you see in this scenario? Also if you could share how you've been reproducing this would be very helpful :)

As you mentioned, exhausting retries hasn't been considered equivalent to an invalid state, and that's probably one of the reasons why we didn't mark an upload invalid when reaching retry limits. I will work with my team to look into it more and see if it's reasonable to refactor that. 

Another option would be to remove the invalid check in the `recover` method. The `recover` method checks the upload status with the server and specifies which bytes has the server persisted so far. That way an upload with exhausted retries could still call on recover and continue.

**Comment by AshleyT3** [comment]
> [cojenco](https://github.com/cojenco) Could you share the exception you see in this scenario?

The following is an example, some text removed for brevity... basically the exceptions were the last ConnectionError wrapping (via args) MaxRetryError of the last internal operation before the ResumableUpload instance detects that the retry limit has been reached:

<pre>
ex
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url ... "))
ex.args[0]
MaxRetryError("HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: ... Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))")
</pre>

When first running into this, at first glance, it seemed as though MaxRetryError might be from ResumableUpload though the wrapping would not make sense as ResumableUpload's would, in theory, be outer most. Obviously, these exceptions are the last observed by ResumableUpload itself, not something it produces.

>  [cojenco](https://github.com/cojenco)  ... could share how you've been reproducing

Certainly, as follows...

1. Using sample similar to initial comment, upload 3MB of data, so something like `bytes([1,2,3]*(1024*1024))` using 1MB chunks (1024*1024).
2. I use a brief retry strategy, something that will cause re-raise after about 10 seconds of retry sleep time, something like this: `ru._retry_strategy = RetryStrategy(max_sleep=30, max_cumulative_retry=10)`
3. Place breakpoint after transmit_next_chunk(...) where the debugger will break after the first successful chunk upload.
4. With network connected, run sample, let initiate(...) and the first transmit_next_chunk(...) succeed, where your breakpoint will be hit afterwards.
5. While at debugger break, unplug your LAN cable from the client.
6. Resume the debugger so the sample code loops back to the top for the second transmit_next_chunk(...). Let this transmit sit running until the specified retry limit has been reached. It will lead to ResumableUpload throwing whatever it last observes, something like the exceptions copy/pasted above. 

As part of my workaround, I track the actual time spent looping/calling both transmit_next_chunk/recover, where if that time exceeds what was specified for max_cumulative_retry, I treat the exception as final and re-raise. I therefore use the ResumableUpload retry capability as a workhorse to keep retrying without the caller having to worry about the details beyond handling any ResumableUpload re-raising.

Once the workaround detects retry limit reached, it throws its own retry exception. It would be nice for ResumableUpload to have its own retry exception to wrap the final inner exception for retry limit reached re-raise case. The ResumableUpload user would then always know what to catch for any/all ResumableUpload retry limit reached situations. 

I notice python-api-core wraps exceptions in its own RetryError exception... 

[class RetryError](https://github.com/googleapis/python-api-core/blob/319c02638682563edc1deb24c5e8ba28d15facab/google/api_core/exceptions.py#L71)

So ResumableUpload might have something like its other exceptions but for retry limit reached... 

```
class RetryStrategyLimitReached(Exception):
    """Error class for inner errors propagated to user
    due to the retry strategy limit having been reached.
    See inner exception for the last inner failure relating
    to timeouts leading to reaching the retry strategy limit.
    """
    ...
```

Stemming from the workaround, I observed that recover uses the same retry duration. In this sense, if one has a super long retry, it can be doubled if transmit_next_chunk fails for max_cumulative_retry, where then recover also fails for, say, close to max_cumulative_retry, after which let's say the network is reconnected and things resume. This sort of leads to the notion that the overall tracked retry limit may be something that has a life beyond any one call to ResumableUpload, or that ResumableUpload could perform both transmit_next_chunk/recover as a single call with a single retry until such time as the retry limit as been reached. 

Relating to that... I really like what you mention about having recover usable regardless of instance upload validity. Such would allow the ResumableUpload user to call it as desired... a sort of resumable "ping" ... where there is no harm/foul for issuing it (with your proposed change in place, of course), yet such would provide assurance that ResumableUpload state matches storage backend.

To be clear, ResumableUpload is working fine... all I'm doing with the workaround is taking control of the retry limit and using the ResumableUpload retry strategy to limit the details that my outside code has to worry about... the outer workaround code does not generally see anything re failures until the retry limit is reached... so it merely needs to handle some details with calling either transmit_next_chunk/recover as desired... but transmit_next_chunk/recover perform all the very useful work. 

All to say, the above details are not some big ask from me... I'm not presently blocked and really like that ResumableUpload was available to use... but perhaps there's some low-hanging fruit to pull the need for the workaround into ResumableUpload... I'll certainly welcome any such changes (without asking strongly as I realize you're likely busy)... other users may appreciate them as well. Thanks for the reviewing info issue, asking for details, and for the library in the first place.
