### ISSUE TITLE
Add request timeout

### ISSUE THREAD

**Issue by farin** [googleapis/google-resumable-media-python#45]
Hi
it seems that our project, which use https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage/google/cloud/storage, is getting stuck during upload.

Although we can't confirm it with absolute certainty, it may be good idea have request timeout in resumable-media anyway.
Questions are:
- do you find a timeout good idea in general?
- should be there some well-chosen conservative implicit timeout by library (or explicit user defined timeout is preferred despite much complicated implementation because this library is only used by other google cloud platform libraries)?

We can provide eg. pull request for default timeout but we rather discuss all first.

**Comment by lukesneeringer** [comment]
I think a sane timeout makes sense.

**Comment by tseaver** [comment]
See also #7.
