### ISSUE TITLE
Import error provides wrong message

### ISSUE THREAD

**Issue by mlissner** [googleapis/google-resumable-media-python#58]
The code here isn't always accurate:

https://github.com/googleapis/google-resumable-media-python/blob/master/google/resumable_media/requests/__init__.py#L664-L673

Basically, it says that a certain version of requests is required, but the `ResolutionError` that's caught can be thrown by other reasons. In my case, I satisfied the requirement for requests, but I had a version conflict in a different module. As pointed out by `pipdeptree` (a tool that makes a tree of your pip dependencies):

```txt
Warning!!! Possibly conflicting dependencies found:
* requests==2.20.0
 - idna [required: >=2.5,<2.8, installed: 2.8]
```

And when I tried to run the ` pkg_resources.require('requests >= 2.18.0')` code myself, I got this error:

```txt
In [2]: pkg_resources.require('requests >= 2.18.0')
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-2-615e205ac6e7> in <module>()
----> 1 pkg_resources.require('requests >= 2.18.0')

/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/pkg_resources/__init__.pyc in require(self, *requirements)
    896         included, even if they were already activated in this working set.
    897         """
--> 898         needed = self.resolve(parse_requirements(requirements))
    899 
    900         for dist in needed:

/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/pkg_resources/__init__.pyc in resolve(self, requirements, env, installer, replace_conflicting, extras)
    787                 # Oops, the "best" so far conflicts with a dependency
    788                 dependent_req = required_by[req]
--> 789                 raise VersionConflict(dist, req).with_context(dependent_req)
    790 
    791             # push the new requirements onto the stack

ContextualVersionConflict: (idna 2.8 (/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages), Requirement.parse('idna<2.8,>=2.5'), set(['requests']))

```

The error message here should be removed and if possible replaced with the message that's thrown by `pkg_resources`.

**Comment by kingkupps** [comment]
As another example of why finer grained error reporting would be helpful here, I recently was using PyInstaller for creating a binary from python scripts (see [this issue](https://github.com/googleapis/google-resumable-media-python/issues/59)). If the error had said something along the lines of "No module 'request' is installed ..." it would have made debugging much easier.

I was operating under the assumption that I had requests packaged correctly but it was the wrong version which was incorrect as it turned out.

**Comment by kurkop** [comment]
Idem.

Hi, for some hours, I had a problem with google-resumable-media. I updated requests to 2.18.0 and doesn't work. Any idea?. Is It a new error?

```  File "/usr/local/lib/python3.5/site-packages/google/cloud/storage/blob.py", line 42, in <module>
    from google.resumable_media.requests import ChunkedDownload
  File "/usr/local/lib/python3.5/site-packages/google/resumable_media/requests/__init__.py", line 673, in <module>
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
ImportError: ``requests >= 2.18.0`` is required by the ``google.resumable_media.requests`` subpackage.```

**Comment by tseaver** [comment]
The "correct" fix is not to re-wrap the exception at all.  As a secondary issue, we also need not to spell out the dependency pin in more than one location.  #83 tackles both of these issues.
