### ISSUE TITLE
Pyinstaller reports that `requests` is not installed.

### ISSUE THREAD

**Issue by Kryptonh4x0r** [googleapis/google-resumable-media-python#65]
I used pyinstaller to convert my .py file to .exe, but as i try to execute the exe it throws the following error:

> Import Error:requests> 2.18.0 is required by the google.resumable media.requests subpackage.

here's the code i used :

`pyinstaller` -F AdminPanel.py
i tried installing it using pip, but it says that its already installed.

Thanks in advance

**Comment by tseaver** [comment]
@Kryptonh4x0r Can you point us to a (possibly sanitized) version of your `AdminPanel.py` script?

**Comment by tseaver** [comment]
Please feel free to reopen if you can provide more information.

**Comment by shahanaz873** [comment]
Hi @tseaver , I am facing same issue while running the exe, Below are my code details

Python version - 3.7.3
pyinstaller version - 3.5
google-resumable-media==0.3.2
requests==2.18.0

    def list_blobs(bucket_name):
    """Lists all the blobs in the bucket."""
    storage_client = storage.Client()
    blobs = storage_client.list_blobs(bucket_name)
    for blob in blobs:
    print(blob.name)


    def download_blob(bucket_name, source_blob_name, destination_file_name):
    """Downloads a blob from the bucket."""
    storage_client = storage.Client()
    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(source_blob_name)
    blob.download_to_filename(destination_file_name)
    print('Blob {} downloaded to {}.'.format(source_blob_name, destination_file_name))

I have created a hook file named hook-google.resumable_media.requests and placed it in pyinstaller hooks folder, but still facing same issue

    from PyInstaller.utils.hooks import copy_metadata
    datas = copy_metadata('requests')
