### ISSUE TITLE
Allow sending extra kwargs through to transport.request

### ISSUE THREAD

**Issue by dhermes** [googleapis/google-resumable-media-python#7]
See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3421#issuecomment-302650580 for context.

/cc @sstepashka

**Comment by plamut** [comment]
I believe this issue can be closed, the `http_request` helper already accepts extra timeout arguments:

https://github.com/googleapis/google-resumable-media-python/blob/c0732e3da68649640ddf2573fa6dc214ea57e299/google/resumable_media/requests/_helpers.py#L101-L109
